baseURL = "https://nav.jobcher.com"
languageCode = "zh-CN"
title = "jobcher网址导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "jobcher"
  description = "jobcher网址导航"
[params.search]
  enable = true
[params.darkmode]
  enable = false