baseURL = "https://nav.bioitee.com"
languageCode = "zh-CN"
title = "jobcher.com 网址导航"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "jobcher"
    description   = "jobcher.com 网址导航"
    siteurl       = "./"
    about         = "https://www.jobcher.com/about"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/jobcher"  
    enablePreLoad = true		    		           # 网站完全打开前预加载动画
    textPreLoad   = "jobcher.com 网址导航" 		           # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			   # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    baiduhmid     = 'efccc04cb44fc49faddac5876180b369'             # 百度统计 hm.src 的 ID

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/logos/jobcher.png"
    searchImageL      = "assets/images/Halloween.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/Halloween.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/logo@2x.png"
    logoExpandDark    = "assets/images/logo@2x.png"
    logoCollapseLight = "assets/images/logos/jobcher.png"
    logoCollapseDark  = "assets/images/logos/jobcher.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'copy© 2019 - {year} By [jobcher](https://www.jobcher.com)'
