# 执行go程序并提交到github
name: nav_list

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  nav_list:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.89.4
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          tree

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Run Go program
        run: |
          go version
          go run main.go
      - name: Commit files
        run: |
          git config --local user.email "13028911306@163.com"
          git config --local user.name "jobcher"
          git add .
          git commit -m "update"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Build with Hugo
        run: |
          hugo -t webstack-hugo -D

      - name: test
        run: |
          tree
          cd docs && tree

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
            PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
            EXTERNAL_REPOSITORY: jobcher/searchweb
            PUBLISH_BRANCH: main
            PUBLISH_DIR: ./docs
            commit_message: ${{ github.event.head_commit.message }}
