# 执行go程序并提交到github
name: nav_list

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  nav_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Run Go program
        run: |
          go version
          go run main.go
      - name: Commit files
        run: |
          git config --local user.email "13028911306@163.com"
          git config --local user.name "jobcher"
          git add .
          git commit -m "update"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
